### ISSUE TITLE
Deleted polls still gets shown on Recent Polls page

### ISSUE THREAD

**Issue by VishnuSanal** [samayapp/samay#213] opened 2024-01-25 16:31 UTC
**Describe the bug**
Deleted polls still gets shown on Recent Polls page

**To Reproduce**
1. Create a poll
2. Delete it from Recent Polls page
4. The poll is still listed, clicking on it leads to a 404

**Comment by swsrkty** [comment] 2024-01-25 17:36
> The poll is still listed, clicking on it leads to a 404

I'm not able to reproduce it; the poll disappears from the page when I deleted. Can you share a GIF maybe? Thanks.

**Comment by swsrkty** [comment] 2024-01-25 18:26
Thanks Vishnu, I'm looking into it.

**Comment by swsrkty** [comment] 2024-01-27 16:04
Fixed in https://github.com/samayapp/samay/commit/f12777efa294a1bb8cdde3d68d59b11baf870ba4. In short, the issue was that we weren't expecting hyphens in poll titles.

**Closed by swsrkty** 2024-01-27 16:04 UTC
